# Generated by Django 6.0.1 on 2026-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("excerpt", models.TextField(max_length=300)),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="posts/")),
            ],
        ),
    ]
